# Name of your blog (this will show up in the RSS feed)
name: daniel.heath.cc

# Short description (will also be used in the RSS feed)
description: Daniel Heath - Blog

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://daniel.heath.cc

# Makes pretty permalinks. See Jekyll docs for alternatives.
permalink: pretty

exclude:
  - '.bundle'
